apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-eviction-protection
webhooks:
- name: pod-eviction-protection.webhook.io
  clientConfig:
    service:
      name: pod-eviction-protection
      namespace: default
      path: "/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lVTzVab1VNQlRFMktjbHV1dng2MEdBUlkxZTdnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FjRzlrTFdWMmFXTjBhVzl1TFhCeWIzUmxZM1JwYjI0dFkyRXdIaGNOTWpVdwpOREl4TVRNek9UUTFXaGNOTXpVd05ERTVNVE16T1RRMVdqQWxNU013SVFZRFZRUUREQnB3YjJRdFpYWnBZM1JwCmIyNHRjSEp2ZEdWamRHbHZiaTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUl4ZlYrdFRsMjdISDgrOXRIK3Z6QmpXM2x1ZWV4d3lvRjBBeFI4QXhtZHFwQlBySU80UnNyTDc4d3lQa1cyRwpIb0c4Rm13dENMMllMYnFYanFtczRIUWRjMVV6QUY4OW5VYkxUN3BIbW8yZGxaaDFlT0VqanozcDBGQ1FXd3VVCnkrckJ6QjJOcXErd1U0RVhQWld5b2RxZnlyNjN1TDBjNHVkYUVaZ0JKaS9kcWR6TjlTdmx6d1ZVOEZkUDNONloKb0s0WURGVEYyNGZrQzRwaVNrQmxZNy9qNkRuRi8wbVBVaG53L0ZVZkRUMDdIaHg1KzZlMGkzbDR4NzQrMlkwQwpoWmJGSGprOXZNQ3lvSm85eWwvQUsxNU9FNXF6YmltNkk3QVRNK25xcG14LzBXWXNIQ3RLZlFQUzRHcXdxT0ViCkIzRmx0YzVnd0lXRUFZVkUxRXZrMG9jQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZIM3R4R1pKc2RGdXNHM0sKQTNJaVBHc0xDQ2YvTUI4R0ExVWRJd1FZTUJhQUZIM3R4R1pKc2RGdXNHM0tBM0lpUEdzTENDZi9NQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdjYmhuS3ZYWkw5VURlc2NwQU56U2llCkVicTBkdk8wV2JGbk1YZGFSWHdjQjZrUlBleXh5YUQ3bzNpeFpEQUNTTDRVam5oYkxTQ09Gc3hhdE9UZWVTNEkKT25DUVRhOUlTeXIwV0RoZlJPTmlOTml3UW9VTnlKSGtJa05iVGk4c0UveGhTeGJycnNQZVR6Z2VxdlpEM0VrQQp4dFZUTlp6TFg3VWRrVUlITUk0bnAxU2xiSWpTMmFRRDYySTVsZzRSdXlUMTZXamt1b2NUMXRsWVpHMDhpSWZuCklCT2pMREdOZWtDaE4xaHhYdDV6WFcxRG43b3hpeDB6RGFpUmNoRStPbHIrWVd5bEhjTWlCdVIwZTlLWUJNT20KeEt4cG5RdDFZaXNTN2I5VjN3dGJvVU1iQTYxOE05RW1oa1NkRWpvQnYyRGMwTWtXZWNuYUJHVHZQR0dpQVFrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - operations: ["DELETE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1"] 