apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-eviction-protection
webhooks:
- name: pod-eviction-protection.webhook.io
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - default
      - kube-system
  clientConfig:
    service:
      name: pod-eviction-protection
      namespace: default
      path: "/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lVUlZCZzNqTlp2R2xRNzVwV2N5NVJ5QjZxY09Rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FjRzlrTFdWMmFXTjBhVzl1TFhCeWIzUmxZM1JwYjI0dFkyRXdIaGNOTWpVdwpOREl5TURjeU9ETXdXaGNOTXpVd05ESXdNRGN5T0RNd1dqQWxNU013SVFZRFZRUUREQnB3YjJRdFpYWnBZM1JwCmIyNHRjSEp2ZEdWamRHbHZiaTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUxTVmJpS0pxZEFzTithLzBQUS84aE45M242VXRsSFVERkNUM2w4aXdJV2pzK29KTXdHU005cU1sOGdvOU9KbApFU0dnQVJGMTV3aVh0OWVkVFF2dXJZdXJ6bjRqTHo5TFpiblNicjdPREZyMFI1V1laOUw1TTJxaGVNQitSbDNKClRNQUZ5UFB3dktFUFJKZ3YzamNmOHZPZEIxUXJZT3BSY0ducmNBaElJbk4yZ291K3N3Y002dU9lenB2REtZeDgKT29KTmJSMWlvVG1zcjNEK3U0MkgvMmErSkhHYUdnVVh3eTc3VnFMUjJOMTBTa3VlRFlwQmJwNlZON29tYXdSUgpZU1hxNVIwa015Q2J3QXNldERKM2dpbkIrbCsvRU9VWTM3V3VVeHQxRndIYWRVWUhCdmlHb1YreHBVV2hNQklMCnFkN2FCTFFaNFhnSEJia2tWTG1ENXdrQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZOUEpCQVpQdGNxVmdCNVEKMHZVTkJ0emdPbTBNTUI4R0ExVWRJd1FZTUJhQUZOUEpCQVpQdGNxVmdCNVEwdlVOQnR6Z09tME1NQThHQTFVZApFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdwa0RqT014UnRVMDFJQXRpSmxiQ09DCkEwK2dnYjlUVkhDMEV3UGFYaGFNdFdLVHoyQTF2elB4OUpDSWpZejFNbmU0WU9DbjRieWhLK2U1bUExZG1pcmMKRGdhUjltQiszeG5hU2tNK2RXcHJnd0d1cUg5bFhoc3pCYzJpMWZSWThlOXowcFFOTFVxczFpSEdaWm1uNnJoRgp5QjNsdEJrTDhxd1Brc2hUTkdyaUZlT0RHaXpNb0lhQlJDNE1sVk5uUmlJbXIxbnpHb1dJWGV5dSt2T0Zmc25BCkhTNDhtaGFmZklISzFWZDNIZXFUMjcvZVpyQ0JYKzM2ZDMrcTJBS0puLzZkYlRpUjRIRmpMU1dNK3BBUWtnM2cKbGtLL0grN3llN2tBaXZudk9lRHhhdVU2blJseVBiZ1lPUEN1VGJUYURRM3N1eUNTL254UEtiM0pScGRlN0pJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - operations: ["DELETE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Fail
  sideEffects: None
  admissionReviewVersions: ["v1"]
  timeoutSeconds: 10